name: Build IzPack Installer

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Create target directory
        run: mkdir -p target

      - name: Build with Maven
        run: |
          mvn clean package -X > build.log 2>&1
          cat build.log

      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: izpack-installer
          path: installer/target/*.jar
          if-no-files-found: error 
