name: Build and Test with Debug Logging

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 1.6 
        uses: actions/setup-java@v1 
        with: 
          java-version: '1.6' 
          distribution: 'zulu' 

      - name: Run Maven Clean Package with Debug Logging
        run: |
          set -o pipefail
          mvn clean package -X | tee build.log
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.25-9/x64
          JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.25-9/x64

      - name: Display Build Log if Exists
        if: failure()
        run: cat build.log || echo "No build log generated."

      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: izpack-installer
          path: installer/target/*.jar
          if-no-files-found: error 
